ALTER TABLE Reservation
	ADD CONSTRAINT pidFK FOREIGN KEY(passengerID)
	REFERENCES Passenger
	ON DELETE SET NULL
	ON UPDATE CASCADE;

ALTER TABLE Reservation
	ADD CONSTRAINT fidFK FOREIGN KEY(flightID)
	REFERENCES Flight
	ON UPDATE CASCADE;

ALTER TABLE CheckIN
	ADD CONSTRAINT ridFK FOREIGN KEY(reservationID)
	REFERENCES Reservation
	ON DELETE CASCADE
	ON UPDATE CASCADE;
